#!/usr/bin/python2
#coding=utf-8
#The Credit For This Code Goes To sumit karki
#If You Wanna Take Credits For This Code, Please Look Yourself Again...
#Reserved2020


import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,requests,mechanize
from multiprocessing.pool import ThreadPool
from requests.exceptions import ConnectionError
from mechanize import Browser


reload(sys)
sys.setdefaultencoding('utf8')
br = mechanize.Browser()
br.set_handle_robots(False)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(),max_time=1)
br.addheaders = [('User-Agent', 'Opera/9.80 (Android; Opera Mini/32.0.2254/85. U; id) Presto/2.12.423 Version/12.16')]


def keluar():
	print "\1b[1;91mExit"
	os.sys.exit()


def acak(b):
    w = 'ahtdzjc'
    d = ''
    for i in x:
        d += '!'+w[random.randint(0,len(w)-1)]+i
    return cetak(d)


def cetak(b):
    w = 'ahtdzjc'
    for i in w:
        j = w.index(i)
        x= x.replace('!%s'%i,'\33[%s;1m'%str(31+j))
    x += '\33[0m'
    x = x.replace('!0','\33[0m')
    sys.stdout.write(x+'\')


def jalan(z):
	for e in z + '\':
		sys.stdout.write(e)
		sys.stdout.flush()
		time.sleep(0.07)

#Dev:love_hacker
##### LOGO #####
logo = """
       \33[1;91m:▒▒▒▒███▒███▒███▒███▒▒▒▒▒▒▒▒▒▒:
      \33[1;92m▒▒▒▒▒▒▒▒█▒█▒█▒▒▒█▒█▒█▒▒▒▒▒▒▒▒▒▒::     
     \33[1;93m:▒▒▒▒▒▒███▒█▒█▒███▒█▒█▒▒▒▒▒▒▒▒▒▒:::      
    \33[1;94m::▒▒▒▒▒▒█▒▒▒█▒█▒█▒▒▒█▒█▒▒▒▒▒▒▒▒▒▒::::      
   \33[1;95m:::▒▒▒▒▒▒███▒███▒███▒███▒▒▒▒▒▒▒▒▒▒:::::         
  \33[1;96m::♧♧♧♧♧♧♧♧♧♧\33[1;91mWhatsapp\33[1;96m♧♧♧♧♧♧♧♧♧♧▒▒▒▒▒▒▒::::        
  \33[1;91m:》》》\33[1;93m+923094161457\33[1;91m《《《▒▒▒▒▒▒▒▒▒▒▒:::::
\33[1;95m♡╭──────────•◈•──────────╮♡\33[1;96m-BlackMafia-\33[1;95m♡╭──────────•◈•──────────╮♡
\33[1;92m..........................BlackMafia......................
\33[1;93m╔╗ ╔╗╔═╦╦╦═╗ ╔╗╔╦═╦╦╗
\33[1;93m║║ ║╚╣║║║║╩╣ ╚╗╔╣║║║║   Nepal
\33[1;93m╚╝ ╚═╩═╩═╩═╝═ ╚╝╚═╩═╝ 
\33[1;95m♡╰──────────•◈•──────────╯♡\33[1;96mBlackMafia\33[1;95m♡╰──────────•◈•──────────╯♡"""

def tik():
	titik = ['.   ','..  ','... ']
	for o in titik:
		print("\\1b[1;93mPlease Wait \1b[1;93m"+o),;sys.stdout.flush();time.sleep(1)


back = 0
berhasil = []
cekpoint = []
oks = []
id = []
listgrup = []
vulnot = "\33[31mNot Vuln"
vuln = "\33[32mVuln"

os.system("clear")
print  """
  \33[1;96m-┈┈┈┈┈┈┈┈┈┈┈╱▔▔▔▔╲┈┈┈┈┈┈┈┈         
  \33[1;96m┈┈┈┈┈┈┈┈┈┈┈▕▕╲┊┊╱▏▏┈┈┈┈┈┈┈        
  \33[1;96m┈┈┈┈┈┈┈┈┈┈┈▕▕▂╱╲▂▏▏┈┈┈┈┈┈┈   
 \33[1;96m ┈┈┈┈┈┈┈┈┈┈┈┈╲┊┊┊┊╱┈┈┈┈┈┈┈┈   
 \33[1;96m ┈┈┈┈┈┈┈┈┈┈┈┈▕╲▂▂╱▏┈┈┈┈┈┈┈┈
 \33[1;96m ┈┈┈┈┈┈┈┈╱▔▔▔▔┊┊┊┊▔▔▔▔╲┈┈┈┈
  \33[1;96m ─────────────•◈•──────────  
   \33[1;92m███████▒▒ sumit Karki on Game▒▒████████
\33[1;95m♡╭──────────•◈•──────────╮♡\33[1;96mBlackMafia\33[1;95m♡╭──────────•◈•──────────╮♡
\33[1;94mAuthor\33[1;91m: \33[1;91mlovehacker
\33[1;94mBlackMafia\33[1;91m: \33[1;91▒▓██████████████]99.9
\33[1;94mFacebook\33[1;91m: \33[1;91mlovehacker
\33[1;94mWhatsapp\33[1;91m: \33[1;91m+923094161457
\33[1;95m♡╰──────────•◈•──────────╯♡\33[1;96mBlackMafia\33[1;95m♡╰──────────•◈•──────────╯♡"""
jalan('              \33[1;96m....................BlackMafia.....................:')
jalan("\33[1;93m   ┈┈┈┈┈┈┈┈╱▔▔▔▔╲┈┈┈┈┈┈┈┈   ")
jalan('\33[1;93m   ┈┈┈┈┈┈┈▕▕╲┊┊╱▏▏┈┈┈┈┈┈┈   ')
jalan('\33[1;93m   ┈┈┈┈┈┈┈▕▕▂╱╲▂▏▏┈┈┈┈┈┈┈   ')
jalan("\33[1;93m   ┈┈┈┈┈┈┈┈╲┊┊┊┊╱┈┈┈┈┈┈┈┈ ")
jalan("\33[1;93m   ┈┈┈┈┈┈┈┈▕╲▂▂╱▏┈┈┈┈┈┈┈┈")
print "\33[1;93m♡─────╱▔▔▔▔┊┊┊┊▔▔▔▔╲───────♡\33[1;96mLogin BlackMafia\33[1;95m♡╰──────────•◈•──────────╯♡"

CorrectUsername = "sumit"
CorrectPassword = "lovehacker"

loop = 'true'
while (loop == 'true'):
    username = raw_input("\33[1;91m🔐 \1b[1;91mTool Username \1b[1;91m»» \1b[1;93m")
    if (username == CorrectUsername):
    	password = raw_input("\33[1;94m🔐 \1b[1;91mTool Password \1b[1;91m»» \1b[1;92m")
        if (password == CorrectPassword):
            print "Logged in successfully as " + username #Dev:love_hacker
	    time.sleep(2)
            loop = 'false'
        else:
            print "\33[1;91mWrong Password"
            os.system('xdg-open https://m.youtube.com/channel/UCRrRgcJjsnNm5Bi5ZenRGnw')
    else:
        print "\33[1;94mWrong Username"
        os.system('xdg-open https://m.youtube.com/channel/UCRrRgcJjsnNm5Bi5ZenRGnw')

def login():
	os.system('clear')
	try:
		toket = open('login.txt','r')
		menu() 
	except (KeyError,IOError):
		os.system('clear')
		print logo
		jalan(' \33[1;92mWarning: \33[1;97mDo Not Use Your Personal Account' )
		jalan(' \33[1;92m   Note: \33[1;97mUse a New Account To Login' )
		print "\33[1;95m♡──────────•◈•──────────♡\33[1;96mBlackMafia\33[1;95m♡──────────•◈•──────────♡"
		print('	   \33[1;94m♡\1b[1;91m》》》》》》LOGIN WITH FACEBOOK《《《《《《\1b[1;94m♡' )
		print('	' )
		id = raw_input('\33[1;96m[+] \1b[1;92mID/Email\1b[1;95m: \1b[1;96m')
		pwd = raw_input('\33[1;96m[+] \1b[1;93mPassword\1b[1;96m: \1b[1;96m')
		tik()
		try:
			br.open('https://m.facebook.com')
		except mechanize.URLError:
			print"\\1b[1;96mThe
